version: '3'
services:
  sbm-api-gateway:
    container_name: sbm-api-gateway
    image: mafeidev/sbm-api-gateway:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - sbm
    depends_on:
      - sbm-eureka-service
  sbm-eureka-service:
    container_name: sbm-eureka-service
    image: mafeidev/sbm-eureka-service:1.0.0
    ports:
      - "8085:8085"
    networks:
      - sbm
  sbm-user-service:
    image: mafeidev/sbm-user-service:1.0.0
    restart: always
    environment:
      - INFO_APP_AUTHOR=MAFEI
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - sbm
    volumes:
      - C:/sharedsaga:/root/stacksaga
    depends_on:
      - sbm-api-gateway
    deploy:
      mode: replicated
      replicas: 2
networks:
  sbm: