version: "3"

services:
  elk_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elk_elasticsearch
    environment:
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  elk_kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: elk_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elk_elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elk_elasticsearch:9200"]'
    depends_on:
      - elk_elasticsearch
    networks:
      - elastic

  elk_logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    container_name: elk_logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
      - elastic
    depends_on:
      - elk_elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local